INSERT INTO links (url, name, description, tags) VALUES 
('https://www.chatpdf.com/', 'ChatPDF', 'Allows you to chat with AI assistants while viewing PDFs', 'AI, PDF, Chat'),
('https://designer.microsoft.com/', 'Microsoft Designer', 'Design tool from Microsoft', 'Design, Graphics'),
('https://chat.openai.com/', 'OpenAI Chat', 'Chat interface for OpenAI''s language models', 'AI, Chat'),
('https://labs.openai.com/', 'OpenAI Labs', 'Playground for testing OpenAI''s AI models', 'AI, Experimentation'),
('https://rytr.me/', 'Rytr', 'AI writing assistant', 'AI, Writing'),
('https://harpa.ai/', 'Harpa', 'AI writing tool', 'AI, Writing'),
('https://www.canva.com/', 'Canva', 'Graphic design tool', 'Design, Graphics'),
('https://studio.polotno.com/', 'Polotno Studio', 'Online design and presentation tool', 'Design, Presentation'),
('https://www.copy.ai/', 'Copy.ai', 'AI copywriting tool', 'AI, Writing, Copywriting'),
('https://www.lalal.ai/', 'Lalal.ai', 'AI audio editing tool', 'AI, Audio'),
('https://podcast.adobe.com/enhance', 'Adobe Podcast Enhance', 'Audio enhancement tool from Adobe', 'Audio, Editing'),
('https://uizard.io/', 'Uizard', 'AI design assistant', 'AI, Design'),
('https://clipdrop.co/relight', 'Clipdrop Relight', 'AI video editing tool', 'AI, Video, Editing'),
('https://www.smartwriter.ai/', 'SmartWriter', 'AI writing assistant', 'AI, Writing'),
('https://playgroundai.com/create', 'PlaygroundAI', 'AI image generation tool', 'AI, Images'),
('https://beta.tome.app/', 'Tome', 'AI note-taking and research assistant', 'AI, Notes, Research'),
('https://marketplace.visualstudio.com/items?itemName=Safurai.Safurai', 'Safurai', 'AI code review extension for VS Code', 'AI, Code Review, VS Code'),
('https://scribblediffusion.com/?utm_source=futurepedia&utm_medium=marketplace&utm_campaign=futurepedia', 'Scribble Diffusion', 'AI image generation from sketches', 'AI, Images, Sketches'),
('https://lexica.art/aperture', 'Lexica Aperture', 'AI image generation and editing tool', 'AI, Images, Editing'),
('https://www.getconch.ai/bypass', 'Conch AI', 'AI bypass tool for Notion, Roam, and Craft', 'AI, Productivity, Bypass'),
('https://www.codeconvert.ai/app', 'CodeConvert.ai', 'AI code converter', 'AI, Code, Conversion'),
('https://magicstudio.com/magiceraser', 'Magic Eraser', 'AI image editing tool', 'AI, Images, Editing'),
('https://www.unscreen.com/', 'Unscreen', 'AI video background removal tool', 'AI, Video, Editing'),
('https://www.bluewillow.ai/', 'Bluewillow.ai', 'AI writing assistant', 'AI, Writing'),
('https://app.humata.ai/', 'Humata', 'AI research assistant', 'AI, Research'),
('https://app.presentations.ai/docs/login', 'Presentations.AI', 'AI presentation creation tool', 'AI, Presentations'),
('https://platform.openai.com/playground/p/default-explain-code', 'OpenAI Explain Code', 'AI code explanation tool from OpenAI', 'AI, Code, Explanation'),
('https://www.perplexity.ai/', 'Perplexity AI', 'AI video editing and creation tool', 'AI, Video'),
('https://www.reimaginehome.ai', 'ReImagine Home AI', 'AI home design tool', 'AI, Design, Home'),
('https://app.simplified.com', 'Simplified', 'AI document summarization tool', 'AI, Summarization'),
('https://docs.google.com/spreadsheets/u/0/d/1QCVpGC9F502lb8pbWBd5vD_VTjw9K9bAOsxILRab13c/htmlview', 'GoogleSheets Link', 'Shared Google Sheets link', 'Spreadsheets, Data'),
('https://firefly.adobe.com/generate/images', 'Adobe Firefly Image Gen', 'AI image generation tool from Adobe', 'AI, Images'),
('https://stunning.so', 'Stunning', 'AI design and presentation tool', 'AI, Design, Presentations'),
('https://app.kaiber.ai', 'Kaiber.ai', 'AI writing assistant', 'AI, Writing'),
('https://app.leonardo.ai/', 'Leonardo.ai', 'AI code generation tool', 'AI, Code'),
('https://spline.design/', 'Spline', '3D design and animation tool', '3D, Design, Animation'),
('https://www.sincode.ai', 'SinCode.ai', 'AI programming assistant', 'AI, Programming'),
('https://firefly.adobe.com/', 'Adobe Firefly', 'AI creative tools from Adobe', 'AI, Creative, Tools'),
('https://fadr.com/', 'Fadr', 'AI facial animation tool', 'AI, Animation, Faces'),
('https://chat.forefront.ai/', 'Forefront Chat', 'AI chat interface', 'AI, Chat'),
('https://niomverse.com/ai-tools', 'NiomVerse AI Tools', 'Directory of AI tools', 'AI, Tools, Directory'),
('https://studio.d-id.com', 'D-ID Studio', 'AI video editing and creation tool', 'AI, Video'),
('https://colab.research.google.com/drive/1n-lGFGIrkJfV38G980sqmAa_5nLAzzj_?usp=sharing#scrollTo=ZOTu5AAS6A9I', 'Colab Notebook', 'Google Colab notebook link', 'Colab, Notebooks, Code'),
('https://beta.elevenlabs.io/speech-synthesis', 'ElevenLabs', 'AI speech synthesis tool', 'AI, Speech, Synthesis'),
('https://replicate.com/nightmareai', 'NightmareAI', 'AI image manipulation tool', 'AI, Images, Manipulation'),
('https://app.wavtool.com/', 'Wavtool', 'Audio editing tool', 'Audio, Editing'),
('https://www.gptminus1.com/', 'GPTMinus1', 'AI text continuation tool', 'AI, Writing, Text'),
('https://www.framer.com/ai', 'Framer AI', 'AI design and prototyping tool', 'AI, Design, Prototyping'),
('https://huggingface.co/spaces/facebook/MusicGen', 'MusicGen', 'AI music generation tool', 'AI, Music'),
('https://lumalabs.ai/dashboard/captures', 'Lumalabs Captures', 'AI video editing tool', 'AI, Video, Editing'),
('https://replicate.com/sczhou/codeformer', 'CodeFormer', 'AI code generation tool', 'AI, Code'),
('https://simplified.com/', 'Simplified', 'AI writing and document assistant', 'AI, Writing, Documents'),
('https://uizard.io/', 'Uizard', 'AI design tool', 'AI, Design'),
('https://x-minus.pro/ai', 'X-Minus Pro', 'AI vocal removal tool', 'AI, Audio, Vocals'),
('https://aws.amazon.com/codewhisperer/', 'AWS CodeWhisperer', 'AI code generation tool from AWS', 'AI, Code, AWS'),
('https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.5.0', 'UltimateVocalRemoverGUI', 'Vocal removal tool', 'Audio, Vocals, Removal'),
('https://wonderdynamics.com/', 'Wonder Dynamics', 'AI video editing and creation tool', 'AI, Video'),
('https://claude.ai/chats', 'Claude.ai', 'AI chatbot interface', 'AI, Chat'),
('https://www.promptvibes.com/', 'PromptVibes', 'AI prompt engineering tool', 'AI, Prompts'),
('https://www.immerse.zone/', 'Immerse Zone', 'AI video editing and creation tool', 'AI, Video'),
('https://ai-midi.com/', 'AI-MIDI', 'AI music generation tool', 'AI, Music'),
('https://threatmap.checkpoint.com/', 'Threat Map', 'Cybersecurity threat map', 'Security, Threats'),
('https://undetectable.ai/', 'Undetectable AI', 'AI content detector', 'AI, Content, Detection'),
('https://www.vondy.com/', 'Vondy', 'AI video editing tool', 'AI, Video, Editing'),
('https://www.castmagic.io/', 'CastMagic', 'AI video creation tool', 'AI, Video'),
('https://www.flux.ai', 'Flux AI', 'AI creative tools', 'AI, Creative, Tools'),
('https://coproducer.output.com/pack-generator', 'CoProduer', 'AI music creation tool', 'AI, Music'),
('https://www.widecanvas.ai/', 'WideCanvas AI', 'AI design tool', 'AI, Design'),
('https://www.trickle.so/', 'Trickle', 'AI writing tool', 'AI, Writing'),
('https://www.blackbox.ai/', 'Blackbox AI', 'AI modeling and deployment platform', 'AI, Modeling, Deployment'),
('https://makersuite.google.com/app/prompts/new_freeform', 'Google MakerSuite', 'AI prompt tool from Google', 'AI, Prompts'),
('https://multimedia.easeus.com/vocal-remover/', 'EaseUS VocalRemover', 'Vocal removal tool', 'Audio, Vocals, Removal'),
('https://ai.invideo.io/', 'InVideo AI', 'AI video editing tool', 'AI, Video, Editing'),
('https://riverside.fm/transcription#', 'Riverside Transcription', 'Audio transcription tool', 'Audio, Transcription'),
('https://pro.splashmusic.com/generate', 'Splash Music', 'AI music generation tool', 'AI, Music'),
('https://library.relume.io/dashboard', 'Relume Library', 'AI asset library', 'AI, Assets, Library'),
('https://webflow.com/', 'Webflow', 'Website builder', 'Web Design, Builder'),
('https://bubble.io/home', 'Bubble', 'No-code app builder', 'No-Code, Apps, Builder'),
('https://riverside.fm/transcription', 'Riverside Transcription', 'Audio transcription tool', 'Audio, Transcription'),
('https://testmail.app/', 'Testmail', 'Temporary email service', 'Email, Temporary'),
('https://twoshot.app/', 'TwoShot', 'AI image editing tool', 'AI, Images, Editing'),
('https://app.kits.ai', 'Kits AI', 'AI writing assistant', 'AI, Writing'),
('https://rows.com/theloko/my-spreadsheets/untitled-2-5zuW4fjWOJvHQteELmo8YR/154f8215-689b-48c5-95d8-9ba6b6156490/view#table1', 'Rows', 'Spreadsheet tool', 'Spreadsheets, Data'),
('https://app.durable.co', 'Durable', 'Note-taking and writing tool', 'Notes, Writing'),
('https://summarist.ai/', 'Summarist AI', 'Text summarization tool', 'AI, Summarization'),
('https://www.aiprm.com/', 'AIPRM', 'AI project management tool', 'AI, Project Management'),
('https://chrome.google.com/webstore/detail/merlin-1-click-access-to/camppjleccjaphfdbohjdohecfnoikec', 'Merlin Browser Extension', 'AI browser extension', 'AI, Browser, Extension'),
('https://www.autodraw.com/', 'AutoDraw', 'AI drawing tool', 'AI, Drawing'),
('https://beta.character.ai/', 'Character AI', 'AI conversational agent', 'AI, Conversation'),
('https://www.tidalflow.health/', 'Tidalflow', 'Health management platform', 'Health, Management'),
('https://writehuman.ai/', 'WriteHuman AI', 'AI writing assistant', 'AI, Writing'),
('https://annotate.tv/', 'Annotate TV', 'Video annotation tool', 'Video, Annotation'),
('https://answerthepublic.com/', 'Answer the Public', 'Keyword research tool', 'Keywords, Research'),
('https://learningstudioai.com/?via=adk334&gad_source=1', 'Learning Studio AI', 'AI learning platform', 'AI, Learning'),
('https://landing-8yljdqazy-humata.vercel.app/', 'Humata Landing', 'Humata AI landing page', 'AI, Landing Page'),
('https://gamma.app/?lng=en', 'Gamma AI', 'AI writing tool', 'AI, Writing'),
('https://www.heygen.com/', 'Heygen', 'AI content creation tool', 'AI, Content'),
('https://theresanaiforthat.com/', 'There''s an AI for That', 'AI tool directory', 'AI, Tools, Directory'),
('https://docs.google.com/spreadsheets/d/15oFP6am-k0cY8Bl_u9RuGgUeaLTOq_gbiA0GI8p6Q7M/edit?usp=drivesdk', 'Google Sheets', 'Shared Google Sheets link', 'Spreadsheets, Data'),
('https://zapier.com/app/dashboard?context=18506946', 'Zapier Dashboard', 'Zapier automation platform', 'Automation, Integration'),
('https://www.compose.ai/', 'Compose AI', 'AI writing assistant', 'AI, Writing'),
('https://sider.ai/', 'Sider AI', 'AI research assistant', 'AI, Research'),
('https://www.grammarly.com/citations', 'Grammarly Citations', 'Citation tool', 'Writing, Citations'),
('https://www.opus.pro/', 'Opus AI', 'AI writing assistant', 'AI, Writing'),
('https://numerous.ai/', 'Numerous AI', 'AI assistant platform', 'AI, Assistants'),
('https://www.udio.com/', 'Udio', 'AI audio editing tool', 'AI, Audio, Editing');
